class ModelConfig:
    MAX_LENGTH_NAME = 200
    MAX_LENGTH_SLUG = 200
    MAX_LENGTH_STATUS = 16
    MAX_LENGTH_KIND = 16
    MAX_LENGTH_HEADING = 255
    MAX_LENGTH_HEADING_ANCHOR = 255
    MAX_LENGTH_ALT_TEXT = 255
    MAX_LENGTH_CAPTION = 255
    MAX_SHORT_QUESTION = 20
    MAX_LENGTH_SHORT_QABLOCK = 20
